# Generated by Django 5.2.8 on 2025-11-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='routes.route')),
            ],
            options={
                'ordering': ['route', 'position'],
                'unique_together': {('route', 'position')},
            },
        ),
    ]
