# Generated by Django 5.2.8 on 2025-11-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='routes.routenode'),
        ),
        migrations.AddField(
            model_name='routenode',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], help_text='Is this node the left or right child of its parent?', max_length=5, null=True),
        ),
    ]
